---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include poppen.iptables_legacy"
      ansible.builtin.include_role:
        name: "poppen.iptables_legacy"
