---
name: CI
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2204
          - debian11
          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Run Molecule tests.
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          NO_IPV6: '1'
